services:

  postgresql:
    container_name: neighborhood_pg_sql
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "1234:5432"
    networks:
      - neighborhood-net
    restart: unless-stopped

  mongodb:
    image: mongo
    container_name: neighborhood_mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    networks:
      - neighborhood-net  # Include MongoDB in the network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: neighborhood_zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - neighborhood-net

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: neighborhood_kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT, PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    networks:
      - neighborhood-net


#KEYCLOAK------------------------
  keycloak-db:
    image: postgres:15
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data  # Ensure this is unique
    networks:
      - neighborhood-net

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    container_name: keycloak_web
    environment:
      KC_DB: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB_URL: jdbc:postgresql://keycloak-db/keycloak
      KC_HOSTNAME: localhost
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_LOG_LEVEL: info
    command: start-dev
    ports:
      - "9090:8080"
    depends_on:
      - keycloak-db
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - neighborhood-net

networks:
  neighborhood-net:
    driver: bridge

volumes:
  postgres:
  mongo:
  keycloak_data:  # Create a volume for Keycloak data
  keycloak_db_data:  # Create a volume for Keycloak's database
