services:

  postgresql:
    container_name: neighborhood_pg_sql
    image: postgres
    environment:
      POSTGRES_USER: dragand
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "1234:5432"
    networks:
      - neighborhood-net
    restart: unless-stopped


  mongodb:
    image: mongo
    container_name: neighborhood_mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dragand
      - MONGO_INITDB_ROOT_PASSWORD=root



  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: neighborhood_zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1     # Needed only for local development
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - neighborhood-net

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: neighborhood_kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT, PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    networks:
      - neighborhood-net





#  zipkin:
#    container_name: zipkin
#    image: openzipkin/zipkin
#    ports:
#      - "9411:9411"
#    networks:
#      - microservices-net


networks:
  neighborhood-net:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongo: