name: Build and Push Discovery Service to Docker

on:
  push:
    branches:
      - main
    paths:
      - 'back-end/services/discovery/**'
  pull_request:
    branches:
      - main
    paths:
      - 'back-end/services/discovery/**'

jobs:
  build-and-push-discovery-service:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Set up JDK 21
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # Use Eclipse Temurin
        java-version: '21'

    - name: Verify Java Version
      run: java -version

    - name: Build Config Server JAR
      run: mvn -f back-end/services/discovery/pom.xml clean package -DskipTests

    - name: Verify Build Output
      run: ls -R back-end/services/discovery/target
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    
    - name: Build Discovery Service Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/discovery:${{ github.sha }} back-end/discovery
    
    - name: Push Discovery Service Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/discovery:${{ github.sha }}
