name: Build and Push Config Service to Docker

on:
  push:
    branches:
      - main
    paths:
      - 'back-end/services/config-server/**'
  pull_request:
    branches:
      - main
    paths:
      - 'back-end/services/config-server/**'

jobs:
  build-and-push-config-service:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

      # Set up JDK 21
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # Use Eclipse Temurin
        java-version: '21'

    - name: Verify Java Version
      run: java -version

    - name: Build Config Server JAR
      run: mvn -f back-end/services/config-server/pom.xml clean package -DskipTests

    - name: Verify Build Output
      run: ls -R back-end/services/config-server/target
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    
    - name: Build Config Service Docker Image
      run: |
        docker build --build-arg ISSUER_URI=${{ secrets.ISSUER_URI }} \
                     --build-arg JWK_SET_URI=${{ secrets.JWK_SET_URI }} \
                     -t ${{ secrets.DOCKER_USERNAME }}/config-server:${{ github.sha }} \
                     back-end/services/config-server
    
    - name: Push Config Service Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/config-server:${{ github.sha }}
